# Generated by Django 4.0.5 on 2022-06-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID компании в BX24')),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ИНН компании')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Компания активна')),
                ('date_last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации')),
                ('responsible', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID ответственого в BX24')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Сфера деятельности')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Отрасль')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Регион')),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Источник компании')),
                ('number_employees', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество сотрудников')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес компании')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район области')),
                ('main_activity', models.CharField(blank=True, max_length=500, null=True, verbose_name='Основной вид деятельности')),
                ('other_activities', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Другие виды деятельности')),
                ('revenue', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Годовой оборот')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Чистая прибыль')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID направления в BX24')),
                ('name', models.CharField(max_length=50, verbose_name='Название направления')),
                ('new', models.BooleanField(db_index=True, default=True, verbose_name='Новое напрвление')),
                ('general_id_bx', models.IntegerField(verbose_name='ID направления в BX24 (для совместимости со старыми направлениями)')),
            ],
            options={
                'verbose_name': 'Направление сделки',
                'verbose_name_plural': 'Направления сделок',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID стадии в BX24')),
                ('abbrev', models.CharField(db_index=True, max_length=35, unique=True, verbose_name='Аббревиатура стадии сделки')),
                ('name', models.CharField(max_length=150, verbose_name='Название стадии сделки')),
                ('won', models.BooleanField(db_index=True, default=False, verbose_name='Сделка завершена успешно')),
                ('status', models.CharField(choices=[('0', 'Подготовка к работе'), ('1', 'В работе'), ('2', 'Успешна'), ('3', 'Провалена')], db_index=True, default='0', max_length=1)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='mainapp.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Стадия сделки',
                'verbose_name_plural': 'Стадии сделки',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id сделки в BX24')),
                ('title', models.CharField(blank=True, db_index=True, max_length=350, null=True, verbose_name='Название сделки')),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания сделки')),
                ('date_modify', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения')),
                ('date_closed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сделки')),
                ('date_last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации')),
                ('closed', models.BooleanField(default=False, verbose_name='Сделка завершена')),
                ('opportunity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма сделки')),
                ('balance_on_payments', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Остаток по оплатам')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Всего оплат на сумму')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='mainapp.company', verbose_name='Компания')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='mainapp.direction', verbose_name='Направление')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='mainapp.stage', verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
