# Generated by Django 4.0.5 on 2022-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'Подготовка к работе'), ('WORK', 'В работе'), ('SUCCESSFUL', 'Успешна'), ('FAILURE', 'Провалена')], db_index=True, default='0', max_length=11),
        ),
    ]
