# Generated by Django 4.0.5 on 2022-06-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_stage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='mainapp.direction', verbose_name='Направление'),
        ),
    ]
