# Generated by Django 4.0.5 on 2022-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_stage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='active',
        ),
        migrations.AddField(
            model_name='company',
            name='requisite_region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Реквизит - район'),
        ),
        migrations.AddField(
            model_name='company',
            name='requisites_city',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Реквизит - город'),
        ),
        migrations.AddField(
            model_name='company',
            name='requisites_province',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Реквизит - область'),
        ),
    ]
