# Generated by Django 4.0.5 on 2022-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_company_active_company_requisite_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID звонка в BX24')),
                ('call_type', models.CharField(blank=True, choices=[('1', 'Исходящий'), ('2', 'Входящий'), ('3', 'Входящий с перенаправлением'), ('4', 'Обратный звонок')], db_index=True, max_length=1, null=True)),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность звонка')),
                ('start_date', models.DateTimeField(verbose_name='Время инициализации звонка')),
                ('activity_id', models.PositiveIntegerField(verbose_name='Идентификатор дела CRM')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='mainapp.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
    ]
