# Generated by Django 4.0.5 on 2022-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='requisite_region',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Реквизит - район'),
        ),
        migrations.AlterField(
            model_name='company',
            name='requisites_city',
            field=models.CharField(blank=True, db_index=True, max_length=750, null=True, verbose_name='Реквизит - город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='requisites_province',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Реквизит - область'),
        ),
    ]
