{
    /* Экология*/
    "NEW":  {"won": false, "status": "PREPARATION"},                    // Скачать КП
    "1":    {"won": false, "status": "PREPARATION"},                    // Согласовать КП
    "2":    {"won": false, "status": "PREPARATION"},                    // КП отправлено
    "3":    {"won": false, "status": "PREPARATION"},                    // Составление договора
    "4":    {"won": false, "status": "PREPARATION"},                    // Договор на согласовании
    "6":    {"won": false, "status": "PREPARATION"},                    // Выставление счета \\ Ожидание оплаты
    "7":    {"won": false, "status": "PREPARATION"},                    // Подписание договора
    "8":    {"won": false, "status": "WORK"},                           // Выбор инженеров
    "15":   {"won": false, "status": "WORK"},                           // Запрос документов
    "16":   {"won": false, "status": "WORK"},                           // В очереди
    "17":   {"won": false, "status": "WORK"},                           // На согласовании
    "19":   {"won": false, "status": "WORK"},                           // Договор завис
    "20":   {"won": false, "status": "WORK"},                           // Работа готова
    "10":   {"won": false, "status": "WORK"},                           // Получение акта выполненных работ
    "21":   {"won": false, "status": "WORK"},                           // Проверка акта выполненных работ
    "22":   {"won": false, "status": "WORK"},                           // ДЗ
    "23":   {"won": false, "status": "WORK"},                           // ПДЗ
    "WON":  {"won": true,  "status": "SUCCESSFUL"},                     // Сделка успешна
    "LOSE": {"won": false, "status": "FAILURE"},                        // Услуга не нужна
    "11":   {"won": false, "status": "FAILURE"},                        // Не устраивают условия договора
    "12":   {"won": false, "status": "FAILURE"},                        // Дорого
    "13":   {"won": false, "status": "FAILURE"},                        // Мониторинг цен для тендера
    "14":   {"won": false, "status": "FAILURE"},                        // Мы не смогли оказать услугу, вернули деньги клиенту

    // СОУТ
    "C2:NEW":                {"won": false, "status": "PREPARATION"},   // Выявление потребности
    "C2:PREPARATION":        {"won": false, "status": "PREPARATION"},   // Отправка КП (Составление +согласование)
    "C2:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},   // Оформление договора (составление + согласование)
    "C2:EXECUTING":          {"won": false, "status": "PREPARATION"},   // Счет выставлен
    "C2:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},   // Счет оплачен
    "C2:1":                  {"won": false, "status": "WORK"},          // Согласование даты замеров
    "C2:2":                  {"won": false, "status": "WORK"},          // Ожидание даты замеров и запрос информации
    "C2:7":                  {"won": false, "status": "WORK"},          // Распределение работы
    "C2:8":                  {"won": false, "status": "WORK"},          // Ожидание готовности работы
    "C2:3":                  {"won": false, "status": "WORK"},          // Получение акта выполненных работ,
    "C2:13":                 {"won": false, "status": "WORK"},          // Проверка акта выполненных работ,
    "C2:14":                 {"won": false, "status": "WORK"},          // ДЗ,
    "C2:15":                 {"won": false, "status": "WORK"},          // ПДЗ,
    "C2:WON":                {"won": true,  "status": "SUCCESSFUL"},    // Оплата получена, акт подписан, сделка завершена,
    "C2:LOSE":               {"won": false, "status": "FAILURE"},       // Услуга не нужна,
    "C2:APOLOGY":            {"won": false, "status": "FAILURE"},       // Не устраивают условия договора,
    "C2:10":                 {"won": false, "status": "FAILURE"},       // Дорого,
    "C2:11":                 {"won": false, "status": "FAILURE"},       // Мониторинг цен для тендера,
    "C2:12":                 {"won": false, "status": "FAILURE"},       // Мы не смогли оказать услугу, вернули деньги клиенту,

    // ЭМИЛ,
    "C4:NEW":                {"won": false, "status": "PREPARATION"},   // Выявление потребности,
    "C4:PREPARATION":        {"won": false, "status": "PREPARATION"},   // Шаблон загружен, согласование заявки,
    "C4:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},   // Заявка обработана,
    "C4:EXECUTING":          {"won": false, "status": "PREPARATION"},   // Скачать КП,
    "C4:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},   // Согласование договора,
    "C4:1":                  {"won": false, "status": "PREPARATION"},   // Договор согласован,
    "C4:2":                  {"won": false, "status": "PREPARATION"},   // Выставление счета \\ Ожидание оплаты,
    "C4:6":                  {"won": false, "status": "PREPARATION"},   // Предоплата поступила,
    "C4:7":                  {"won": false, "status": "WORK"},          // Работа готова,
    "C4:8":                  {"won": false, "status": "WORK"},          // Получение акта выполненных работ,
    "C4:9":                  {"won": false, "status": "WORK"},          // Проверка акта выполненных работ,
    "C4:10":                 {"won": false, "status": "WORK"},          // ДЗ,
    "C4:11":                 {"won": false, "status": "WORK"},          // ПДЗ,
    "C4:WON":                {"won": true,  "status": "SUCCESSFUL"},    // Оплата получена, акт подписан, сделка завершена,
    "C4:LOSE":               {"won": false, "status": "FAILURE"},       // Услуга не нужна,
    "C4:APOLOGY":            {"won": false, "status": "FAILURE"},       // Не устраивают условия договора,
    "C4:3":                  {"won": false, "status": "FAILURE"},       // Дорого,
    "C4:4":                  {"won": false, "status": "FAILURE"},       // Мониторинг цен для тендера,
    "C4:5":                  {"won": false, "status": "FAILURE"},       // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Доступная среда,
    "C6:NEW":                {"won": false, "status": "PREPARATION"},   // Выявление потребности,
    "C6:PREPARATION":        {"won": false, "status": "PREPARATION"},   // Подготовка спецификации (Составление сметы+Согласова
    "C6:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},   // Оформление договора,
    "C6:EXECUTING":          {"won": false, "status": "PREPARATION"},   // Счет на предоплату,
    "C6:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},   // Счет оплачен,
    "C6:1":                  {"won": false, "status": "WORK"},          // В работе,
    "C6:2":                  {"won": false, "status": "WORK"},          // Ожидание готовности работы,
    "C6:3":                  {"won": false, "status": "WORK"},          // Получение акта выполненных работ,
    "C6:7":                  {"won": false, "status": "WORK"},          // Проверка акта выполненных работ,
    "C6:8":                  {"won": false, "status": "WORK"},          // ДЗ,
    "C6:9":                  {"won": false, "status": "WORK"},          // ПДЗ,
    "C6:WON":                {"won": true,  "status": "SUCCESSFUL"},    // Оплата получена, акт подписан, сделка завершена,
    "C6:LOSE":               {"won": false, "status": "FAILURE"},       // Услуга не нужна,
    "C6:APOLOGY":            {"won": false, "status": "FAILURE"},       // Не устраивают условия договора,
    "C6:4":                  {"won": false, "status": "FAILURE"},       // Дорого,
    "C6:5":                  {"won": false, "status": "FAILURE"},       // Мониторинг цен для тендера,
    "C6:6":                  {"won": false, "status": "FAILURE"},       // Мы не смогли оказать услугу, вернули деньги клиенту,

    // МОЗ (сделки создавать в ПБ И МОЗ),
    "C8:NEW":                {"won": false, "status": "PREPARATION"},   // Выявление потребности,
    "C8:PREPARATION":        {"won": false, "status": "PREPARATION"},   // Шаблон загружен, согласование заявки,
    "C8:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},   // Заявка обработана,
    "C8:EXECUTING":          {"won": false, "status": "PREPARATION"},   // Скачать КП,
    "C8:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},   // Договор отправлен,
    "C8:1":                  {"won": false, "status": "PREPARATION"},   // Договор согласован,
    "C8:2":                  {"won": false, "status": "PREPARATION"},   // Счет на предоплату,
    "C8:3":                  {"won": false, "status": "PREPARATION"},   // Предоплата поступила,
    "C8:4":                  {"won": false, "status": "WORK"},          // Работа готова,
    "C8:5":                  {"won": false, "status": "WORK"},          // Получение акта выполненных работ,
    "C8:9":                  {"won": false, "status": "WORK"},          // Проверка акта выполненных работ,
    "C8:10":                 {"won": false, "status": "WORK"},          // ДЗ,
    "C8:11":                 {"won": false, "status": "WORK"},          // ПДЗ,
    "C8:WON":                {"won": true,  "status": "SUCCESSFUL"},    // Оплата получена, акт подписан, сделка завершена,
    "C8:LOSE":               {"won": false, "status": "FAILURE"},       // Услуга не нужна,
    "C8:APOLOGY":            {"won": false, "status": "FAILURE"},       // Не устраивают условия договора,
    "C8:6":                  {"won": false, "status": "FAILURE"},       // Дорого,
    "C8:7":                  {"won": false, "status": "FAILURE"},       // Мониторинг цен для тендера,
    "C8:8":                  {"won": false, "status": "FAILURE"},       // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Обучение,
    "C10:NEW":                {"won": false, "status": "PREPARATION"},  // Подготовка КП,
    "C10:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Согласование КП,
    "C10:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление договора,
    "C10:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Согласование договора,
    "C10:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты,
    "C10:3":                  {"won": false, "status": "WORK"},         // Распределение работы,
    "C10:4":                  {"won": false, "status": "WORK"},         // Ожидание готовности работы,
    "C10:12":                 {"won": false, "status": "WORK"},         // Окончательные расчеты,
    "C10:5":                  {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C10:9":                  {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C10:10":                 {"won": false, "status": "WORK"},         // ДЗ,
    "C10:11":                 {"won": false, "status": "WORK"},         // ПДЗ,
    "C10:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C10:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C10:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C10:6":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C10:7":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C10:8":                  {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,

    // ПК (создавайте сделки в воронке ПК NEW),
    "C12:NEW":           {"won": false, "status": "PREPARATION"},       // Скачать КП,
    "C12:PREPARATION":   {"won": false, "status": "PREPARATION"},       // Отправка КП и согласование,
    "C12:EXECUTING":     {"won": false, "status": "PREPARATION"},       // Составление и согласование договора,
    "C12:FINAL_INVOICE": {"won": false, "status": "PREPARATION"},       // Договор согласован,
    "C12:11":            {"won": false, "status": "PREPARATION"},       // Выставление счета \\ Ожидание оплаты,
    "C12:13":            {"won": false, "status": "WORK"},              // Дата замеров \\ Распределение,
    "C12:14":            {"won": false, "status": "WORK"},              // Проведение замеров,
    "C12:15":            {"won": false, "status": "WORK"},              // Выполнение работы,
    "C12:17":            {"won": false, "status": "WORK"},              // Получение акта выполненных работ,
    "C12:19":            {"won": false, "status": "WORK"},              // Проверка акта выполненных работ,
    "C12:20":            {"won": false, "status": "WORK"},              // ДЗ,
    "C12:21":            {"won": false, "status": "WORK"},              // ПДЗ,
    "C12:WON":           {"won": true,  "status": "SUCCESSFUL"},        // Оплата получена, акт подписан, сделка завершена,
    "C12:LOSE":          {"won": false, "status": "FAILURE"},           // Услуга не нужна,
    "C12:18":            {"won": false, "status": "FAILURE"},           // Не устраивают условия договора,
    "C12:8":             {"won": false, "status": "FAILURE"},           // Дорого,
    "C12:9":             {"won": false, "status": "FAILURE"},           // Мониторинг цен для тендера,
    "C12:10":            {"won": false, "status": "FAILURE"},           // Мы не смогли оказать услугу, вернули деньги клиенту,


    // Энергоаудит,
    "C14:NEW":                {"won": false, "status": "PREPARATION"},  // Скачать КП,
    "C14:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Отправка КП и согалсование,
    "C14:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление и согласование договора,
    "C14:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},  // Договор согласован,
    "C14:1":                  {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты,
    "C14:2":                  {"won": false, "status": "PREPARATION"},  // Опросник отправлен,
    "C14:3":                  {"won": false, "status": "WORK"},         // Передан в работу,
    "C14:4":                  {"won": false, "status": "WORK"},         // Получение подписи тит.листа,
    "C14:6":                  {"won": false, "status": "WORK"},         // Получение паспорта,
    "C14:7":                  {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C14:11":                 {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C14:12":                 {"won": false, "status": "WORK"},         // ДЗ,
    "C14:13":                 {"won": false, "status": "WORK"},         // ПДЗ,
    "C14:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C14:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C14:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C14:8":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C14:9":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C14:10":                 {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,

    // ПБ и МОЗ,
    "C16:NEW":           {"won": false, "status": "PREPARATION"},       // Скачать КП,
    "C16:8":             {"won": false, "status": "PREPARATION"},       // Согласовать КП(нач ПБ),
    "C16:9":             {"won": false, "status": "PREPARATION"},       // Отправить КП и согласовать,
    "C16:PREPARATION":   {"won": false, "status": "PREPARATION"},       // Составление договора,
    "C16:14":            {"won": false, "status": "PREPARATION"},       // Согласование договора,
    "C16:FINAL_INVOICE": {"won": false, "status": "PREPARATION"},       // Выставление счета \\ Ожидание оплаты,
    "C16:13":            {"won": false, "status": "WORK"},              // Распределение работы,
    "C16:2":             {"won": false, "status": "WORK"},              // Выполнение работы,
    "C16:4":             {"won": false, "status": "WORK"},              // Получение акта выполненных работ,
    "C16:10":            {"won": false, "status": "WORK"},              // Проверка акта выполненных работ,
    "C16:11":            {"won": false, "status": "WORK"},              // ДЗ,
    "C16:12":            {"won": false, "status": "WORK"},              // ПДЗ,
    "C16:WON":           {"won": true,  "status": "SUCCESSFUL"},        // Оплата получена, акт подписан, сделка завершена,
    "C16:LOSE":          {"won": false, "status": "FAILURE"},           // Услуга не нужна,
    "C16:APOLOGY":       {"won": false, "status": "FAILURE"},           // Не устраивают условия договора,
    "C16:5":             {"won": false, "status": "FAILURE"},           // Дорого,
    "C16:6":             {"won": false, "status": "FAILURE"},           // Мониторинг цен для тендера,
    "C16:7":             {"won": false, "status": "FAILURE"},           // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Аудит и Аутсорсинг
    "C18:NEW":                {"won": false, "status": "PREPARATION"},  // Скачать шаблон заявки,
    "C18:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Заявка в обработке,
    "C18:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Подготовка и отправка КП,
    "C18:6":                  {"won": false, "status": "PREPARATION"},  // Согласование КП,
    "C18:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Составление и согласование договора,
    "C18:7":                  {"won": false, "status": "PREPARATION"},  // Договор согласован,
    "C18:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},  // Счет на предоплату,
    "C18:1":                  {"won": false, "status": "WORK"},         // В работе,
    "C18:2":                  {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C18:8":                  {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C18:9":                  {"won": false, "status": "WORK"},         // ДЗ,
    "C18:10":                 {"won": false, "status": "WORK"},         // ПДЗ,
    "C18:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C18:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C18:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C18:3":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C18:4":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C18:5":                  {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Аутсорсинг
    "C20:NEW":     {"won": false, "status": "WORK"},                    // Формирование и выполнение задачи инженером,
    "C20:1":       {"won": false, "status": "WORK"},                    // Выставление счета \\ Ожидание оплаты,
    "C20:2":       {"won": false, "status": "WORK"},                    // Получение акта выполненных работ,
    "C20:3":       {"won": false, "status": "WORK"},                    // Проверка акта выполненных работ,
    "C20:WON":     {"won": true,  "status": "SUCCESSFUL"},              // Сделка успешна,
    "C20:LOSE":    {"won": false, "status": "FAILURE"},                 // Сделка провалена,
    "C20:APOLOGY": {"won": false, "status": "FAILURE"},                 // Анализ причины провала,

    // Юридические Услуги,
    "C21:NEW":                {"won": false, "status": "WORK"},         // Согласование с
    "C21:PREPAYMENT_INVOICE": {"won": false, "status": "WORK"},         // Выставление сч
    "C21:WON":                {"won": true, "status": "SUCCESSFUL"},    // Сделка успешна
    "C21:LOSE":               {"won": false, "status": "FAILURE"},      // Сделка провале
    "C21:APOLOGY":            {"won": false, "status": "FAILURE"},      // Дорого,

    // СОУТ 2.0,
    "C25:NEW":                {"won": false, "status": "PREPARATION"},  // Подготовка КП,
    "C25:6":                  {"won": false, "status": "PREPARATION"},  // Скидка от РОП,
    "C25:10":                 {"won": false, "status": "PREPARATION"},  // Отправка КП клиенту,
    "C25:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Согласование КП с клиентом,
    "C25:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление договора,
    "C25:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты,
    "C25:19":                 {"won": false, "status": "PREPARATION"},  // Подписание договора,
    "C25:7":                  {"won": false, "status": "WORK"},         // Принятие у клиента пакета документов,
    "C25:8":                  {"won": false, "status": "WORK"},         // Ожидание замеров,
    "C25:9":                  {"won": false, "status": "WORK"},         // Распределение работы,
    "C25:11":                 {"won": false, "status": "WORK"},         // Ожидание готовности работы,
    "C25:12":                 {"won": false, "status": "WORK"},         // Окончательные расчеты,
    "C25:13":                 {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C25:14":                 {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C25:16":                 {"won": false, "status": "WORK"},         // ДЗ,
    "C25:17":                 {"won": false, "status": "WORK"},         // ПДЗ,
    "C25:18":                 {"won": false, "status": "WORK"},         // Отчётность ФГИС,
    "C25:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C25:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C25:4":                  {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C25:1":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C25:2":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C25:3":                  {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,
    "C25:15":                 {"won": false, "status": "FAILURE"},      // Нестандартный договор \\ отклонено,

    // Паспортизация фасадов,
    "C29:NEW":                {"won": false, "status": "PREPARATION"},  // C29:NEW
    "C29:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Отправка КП,
    "C29:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление и согласование договора,
    "C29:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты,
    "C29:FINAL_INVOICE":      {"won": false, "status": "WORK"},         // Распределение работы,
    "C29:1":                  {"won": false, "status": "WORK"},         // Выполнение работы,
    "C29:2":                  {"won": false, "status": "WORK"},         // Согласование работы,
    "C29:3":                  {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C29:4":                  {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C29:5":                  {"won": false, "status": "WORK"},         // ДЗ,
    "C29:6":                  {"won": false, "status": "WORK"},         // ПДЗ,
    "C29:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C29:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C29:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C29:7":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C29:8":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C29:9":                  {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Орган инспекции,
    "C31:NEW":                {"won": false, "status": "PREPARATION"},  // Выявление потребностей,
    "C31:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление и согласование договора:,
    "C31:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты,
    "C31:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},  // Запрос необходимых для проведения инспекции документов,
    "C31:1":                  {"won": false, "status": "PREPARATION"},  // Составление, анализ и согласование заявки,
    "C31:2":                  {"won": false, "status": "WORK"},         // Распределение работы,
    "C31:3":                  {"won": false, "status": "WORK"},         // Выполнение работы,
    "C31:4":                  {"won": false, "status": "WORK"},         // Подготовка акта и передача результатов инспекции и документов заказчику,
    "C31:6":                  {"won": false, "status": "WORK"},         // Получение акт выполненных работ,
    "C31:7":                  {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C31:8":                  {"won": false, "status": "WORK"},         // ДЗ,
    "C31:9":                  {"won": false, "status": "WORK"},         // ПДЗ,
    "C31:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Оплата получена, акт подписан, сделка завершена,
    "C31:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C31:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C31:10":                 {"won": false, "status": "FAILURE"},      // Дорого,
    "C31:11":                 {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C31:12":                 {"won": false, "status": "FAILURE"},      // Мы не смогли оказать услугу, вернули деньги клиенту,

    // Оценка проф. рисков,
    "C33:NEW":                {"won": false, "status": "PREPARATION"},  // Подготовка КП,
    "C33:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Согласование КП,
    "C33:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Составление договора,
    "C33:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Согласование договора,
    "C33:FINAL_INVOICE":      {"won": false, "status": "PREPARATION"},  // Выставление счета \\ Ожидание оплаты
    "C33:1":                  {"won": false, "status": "WORK"},         // Распределение работы,
    "C33:2":                  {"won": false, "status": "WORK"},         // Выполнение работы,
    "C33:7":                  {"won": false, "status": "WORK"},         // Окончательные расчеты,
    "C33:3":                  {"won": false, "status": "WORK"},         // Получение акта выполненных работ,
    "C33:4":                  {"won": false, "status": "WORK"},         // Проверка акта выполненных работ,
    "C33:5":                  {"won": false, "status": "WORK"},         // ДЗ,
    "C33:6":                  {"won": false, "status": "WORK"},         // ПДЗ,
    "C33:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Сделка успешна,
    "C33:LOSE":               {"won": false, "status": "FAILURE"},      // Сделка провалена,
    "C33:APOLOGY":            {"won": false, "status": "FAILURE"},      // Анализ причины провала,

    // ПК NEW,???????????????????????????????????
    "C37:NEW":         {"won": false, "status": "PREPARATION"},         // Согласование коммерческих условий,
    "C37:PREPARATION": {"won": false, "status": "PREPARATION"},         // Составление договора,
    "C37:EXECUTING":   {"won": false, "status": "PREPARATION"},         // Согласование договора,
    "C37:1":           {"won": false, "status": "PREPARATION"},         // Выставление счета/ Ожидание оплаты,
    "C37:2":           {"won": false, "status": "WORK"},                // Ожидание замеров,
    "C37:3":           {"won": false, "status": "WORK"},                // Распределение работ,
    "C37:4":           {"won": false, "status": "WORK"},                // Ожидание готовности,
    "C37:5":           {"won": false, "status": "WORK"},                // Окончательные расчеты,
    "C37:6":           {"won": false, "status": "WORK"},                // Получение акта выполненных работ,
    "C37:7":           {"won": false, "status": "WORK"},                // Проверка акта выполненных работ,
    "C37:WON":         {"won": true,  "status": "SUCCESSFUL"},          // Оплата получена, акт подписан, сделка завершена,
    "C37:LOSE":        {"won": false, "status": "FAILURE"},             // Сделка провалена,
    "C37:APOLOGY":     {"won": false, "status": "FAILURE"},             // Анализ причины провала,

    // Отдел продаж,
    "C43:NEW":                {"won": false, "status": "PREPARATION"},  // Новая сделка,
    "C43:PREPARATION":        {"won": false, "status": "PREPARATION"},  // Составление договора,
    "C43:PREPAYMENT_INVOICE": {"won": false, "status": "PREPARATION"},  // Согласование договора,
    "C43:EXECUTING":          {"won": false, "status": "PREPARATION"},  // Выставление счета/ Подготовка документов,
    "C43:8":                  {"won": false, "status": "PREPARATION"},  // Запрос доп. информации,
    "C43:10":                 {"won": false, "status": "PREPARATION"},  // Принятие в работу,
    "C43:7":                  {"won": false, "status": "WORK"},         // В работе,
    "C43:1":                  {"won": false, "status": "WORK"},         // Подписание акта,
    "C43:2":                  {"won": false, "status": "WORK"},         // Проверка акта,
    "C43:9":                  {"won": false, "status": "WORK"},         // Окончательные расчеты,
    "C43:WON":                {"won": true,  "status": "SUCCESSFUL"},   // Сделка успешна,
    "C43:LOSE":               {"won": false, "status": "FAILURE"},      // Услуга не нужна,
    "C43:APOLOGY":            {"won": false, "status": "FAILURE"},      // Не устраивают условия договора,
    "C43:3":                  {"won": false, "status": "FAILURE"},      // Дорого,
    "C43:4":                  {"won": false, "status": "FAILURE"},      // Мониторинг цен для тендера,
    "C43:5":                  {"won": false, "status": "FAILURE"},      // Мы не можем оказать услугу,
    "C43:6":                  {"won": false, "status": "FAILURE"},      // Нестандартный договор/ Отклонено,
}